name       : python-xlib
version    : 0.23
release    : 4
source     :
    - https://github.com/python-xlib/python-xlib/releases/download/0.23/python-xlib-0.23.tar.bz2 : c3deb8329038620d07b21be05673fa5a495dd8b04a2d9f4dca37a3811d192ae4
license    : LGPL-2.1-or-later
component  : programming.python
summary    : A library for writing low-level X Windows clients
description: |
    The Python X Library is a complete X11 client-side implementation, written in pure Python. It can be used to write low-levelish X Windows client applications in Python.
replaces   : python3-xlib
builddeps  :
    - python-setuptools
    - python-setuptools-scm
rundeps    :
    - python-six
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
