name       : python-xlib
version    : '0.32'
release    : 11
source     :
    - https://github.com/python-xlib/python-xlib/releases/download/0.32/python-xlib-0.32.tar.gz : 20e1382f8a98d8ed0facfa45415c46fd0c8eeb6f9996e58c22d3382a4ed6e37b
homepage   : https://github.com/python-xlib/python-xlib
license    : LGPL-2.1-or-later
component  : programming.python
summary    : A library for writing low-level X Windows clients
description: |
    The Python X Library is a complete X11 client-side implementation, written in pure Python. It can be used to write low-levelish X Windows client applications in Python.
replaces   : python3-xlib
builddeps  :
    - harfbuzz
    - python-mock
    - python-nose
    - python-setuptools-scm
    - python3-tkinter
    - xorg-server-xvfb
rundeps    :
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test runtests.py
