name       : python-xlib
version    : '0.27'
release    : 6
source     :
    - https://github.com/python-xlib/python-xlib/releases/download/0.27/python-xlib-0.27.tar.bz2 : a90667c70905c6ef0754c8a09fa61acbc1e1b7ddb946d527831800d7cbfe9348
homepage   : https://github.com/python-xlib/python-xlib
license    : LGPL-2.1-or-later
component  : programming.python
summary    : A library for writing low-level X Windows clients
description: |
    The Python X Library is a complete X11 client-side implementation, written in pure Python. It can be used to write low-levelish X Windows client applications in Python.
replaces   : python3-xlib
builddeps  :
    - harfbuzz
    - python-mock
    - python-nose
    - python-setuptools-scm
    - xorg-server-xvfb
rundeps    :
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test runtests.py
