name       : python-xlib
version    : 0.14
release    : 1
source     :
    - http://internode.dl.sourceforge.net/project/python-xlib/python-xlib/0.14/python-xlib-0.14.tar.gz : 4771b0b6a605e0197ece5432fa601c61df724b32544239f463a867200f2160eb
license    : GPL-2.0
summary    : A library for writing low-level X Windows clients
description: |
    A library for writing low-level X Windows clients
builddeps  :
setup      : |
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
