name       : python-xlib
version    : '0.29'
release    : 7
source     :
    - https://github.com/python-xlib/python-xlib/releases/download/0.29/python-xlib-0.29.tar.gz : e4bcb756f4aa05be7b82ee21de0ba04d73414018727b42ebd9fbcf409ea75d13
homepage   : https://github.com/python-xlib/python-xlib
license    : LGPL-2.1-or-later
component  : programming.python
summary    : A library for writing low-level X Windows clients
description: |
    The Python X Library is a complete X11 client-side implementation, written in pure Python. It can be used to write low-levelish X Windows client applications in Python.
replaces   : python3-xlib
builddeps  :
    - harfbuzz
    - python-mock
    - python-nose
    - python-setuptools-scm
    - xorg-server-xvfb
rundeps    :
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test runtests.py
